# --- DB Docker (Configurazione per container) ---
# Usiamo 'db' come host perché è il nome del servizio nel docker-compose
spring.datasource.url=jdbc:postgresql://localhost:10020/prenotazioni
spring.datasource.username=prenotazioni
spring.datasource.password=prenotazioni
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT secret key
app.jwt-secret=jwtSecretKeyDeveSuperareLunghezzaMinimaPerHS512AlmenoTrentadueBytesLungo

# Server
server.port=10010

# Configurazione Multipart (Fondamentale per l'upload di file DXF)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Configurazione Hikari Connection Pool
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5
spring.datasource.hikari.minimumIdle=2
spring.datasource.hikari.idleTimeout=300000
spring.datasource.hikari.maxLifetime=600000
spring.datasource.hikari.leakDetectionThreshold=300000
spring.datasource.hikari.keepaliveTime=60000
spring.datasource.hikari.autoCommit=false

# Mail (Configurazione vuota come da tua richiesta)
spring.mail.username=
spring.mail.password=