# --- DB locale Docker ---
spring.datasource.url=jdbc:postgresql://db:5432/prenotazioni
spring.datasource.username=prenotazioni
spring.datasource.password=prenotazioni

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


#spring.profiles.include=secrets

# Server
server.port=10010

# JWT secret key
app.jwt-secret=jwtSecretKeyDeveSuperareLunghezzaMinimaPerHS512AlmenoTrentadueBytesLungo
 
# Mail (Creare utenza)
spring.mail.username=
spring.mail.password=
 
 
# Configurazione Hikari Connection Pool
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5
spring.datasource.hikari.minimumIdle=2
spring.datasource.hikari.idleTimeout=300000
spring.datasource.hikari.maxLifetime=600000
spring.datasource.hikari.leakDetectionThreshold=300000
spring.datasource.hikari.keepaliveTime=60000
spring.datasource.hikari.autoCommit=false
spring.datasource.testWhileIdle=true
spring.datasource.validationQuery=SELECT 1

# Inizializzazione automatica dati (impostare a false per disattivare)
# Inizializzazione automatica dati
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
app.init-data=false
