services:
  db:
    image: postgres:16
    restart: always
    container_name: PrenotazioniDB
    environment:
      POSTGRES_DB: prenotazioni
      POSTGRES_USER: prenotazioni
      POSTGRES_PASSWORD: prenotazioni
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "10020:5432"
    networks:
      - prenotazioni-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U prenotazioni -d prenotazioni" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend/exprv
    container_name: PrenotazioniBackend
    ports:
      - "10010:10010"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/prenotazioni
      - SPRING_DATASOURCE_USERNAME=prenotazioni
      - SPRING_DATASOURCE_PASSWORD=prenotazioni
    depends_on:
      db:
        condition: service_healthy
      mailpit:
        condition: service_started
    networks:
      - prenotazioni-net
    volumes:
      - ./backend/uploads:/backend/uploads

  frontend:
    build:
      context: ./frontend
    container_name: PrenotazioniFrontEnd
    ports:
      - "10000:80"
    depends_on:
      - backend
    networks:
      - prenotazioni-net

  mailpit:
    image: axllent/mailpit:latest
    container_name: PrenotazioniMailHog
    ports:
      - "1025:1025"
      - "10030:8025"
    networks:
      - prenotazioni-net

volumes:
  postgres_data:


networks:
  prenotazioni-net:
    driver: bridge
