services:
  db:
    image: postgres:16
    restart: always
    container_name: PrenotazioniDB
    environment:
      POSTGRES_DB: prenotazioni
      POSTGRES_USER: prenotazioni
      POSTGRES_PASSWORD: prenotazioni
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "10020:5432"
    networks:
      - prenotazioni-net

  backend:
    build:
      context: ./backend/exprv
    container_name: PrenotazioniBackend
    ports:
      - "10010:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/prenotazioni
      - SPRING_DATASOURCE_USERNAME=prenotazioni
      - SPRING_DATASOURCE_PASSWORD=prenotazioni
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - prenotazioni-net

  frontend:
    build:
      context: ./frontend
    container_name: PrenotazioniFrontEnd
    ports:
      - "10000:80"
    depends_on:
      - backend
    networks:
      - prenotazioni-net

volumes:
  postgres_data:

networks:
  prenotazioni-net:
    driver: bridge