package com.prenotazioni.exprivia.exprv.enumerati;

public enum AppAuthority {
    // Navigazione e viste di base
    ACTION_DASHBOARD_VIEW,

    // Prenotazioni
    ACTION_RESERVATION_CREATE_OWN,
    ACTION_RESERVATION_CREATE_ANY,
    ACTION_RESERVATION_READ_OWN,
    ACTION_RESERVATION_READ_ANY,
    ACTION_RESERVATION_UPDATE_OWN,
    ACTION_RESERVATION_UPDATE_ANY,
    ACTION_RESERVATION_DELETE_OWN,
    ACTION_RESERVATION_DELETE_ANY,
    ACTION_RESERVATION_APPROVE,
    ACTION_RESERVATION_EXPORT,
    ACTION_MEETINGROOM_BOOK,

    // Utenti
    ACTION_USER_CREATE,
    ACTION_USER_READ,
    ACTION_USER_UPDATE_OWN,
    ACTION_USER_UPDATE_ANY,
    ACTION_USER_DELETE_OWN,
    ACTION_USER_DELETE_ANY,
    ACTION_USER_APPROVE,

    // Planimetrie (Location, Building, Floor, Room, Workspace)
    ACTION_FLOORPLAN_CREATE,
    ACTION_FLOORPLAN_READ,
    ACTION_FLOORPLAN_UPDATE,
    ACTION_FLOORPLAN_DELETE,

    // Badge e Permessi HRBAC
    ACTION_BADGE_CREATE,
    ACTION_BADGE_READ,
    ACTION_BADGE_UPDATE,
    ACTION_BADGE_DELETE,

    // Ruoli Base Consigliati (Questi erediteranno le varie azioni)
    ROLE_GUEST,
    ROLE_USER,
    ROLE_HR,
    ROLE_MANAGER,
    ROLE_ADMIN
}
